# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0003_auto_20171215_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_day',
        ),
    ]
